version: "3.9"
services:
  rasa:
    build: .
    container_name: rasa
    command: ['run', '--enable-api']
    ports:
      - 5005:5005
    networks:
      - bykstack
networks:
  bykstack:
    name: bykstack
    driver: bridge
